### ISSUE TITLE
Task that fetch previous beacon summary has the default timeout

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#1077]
### Describe the problem you discovered

In the function `BeaconChain.fetch_and_aggregate_summaries` the `Task.async_stream` has the default timeout.
This can be a problem as the beacon summary can take more than 5 sec to be fetched depending on it's size

### Describe the solution you'd like

We should increase this timeout to handle possible slow node.

**Comment by samuelmanzanera** [comment]
My take would be instead to increase the timeout for the Task.async in the node beacon summaries retrieval we should have a better management of the streaming upfront
 
For example, instead of doing :
- get addresses by node
-Task async by node
-Chunk addresses
- Task async by chunk 
- Fetch

To do something like:
- get addresses by node
- chunk
- Task async by chunk
- Fetch

First we remove one level of process creation and we are still leveraging standard timeout which is a good for load retention and protect the resources. Hence the first Task async will have a smaller scope, and less risk to timeout.
