### ISSUE TITLE
Internal Error in the Explorer

### ISSUE THREAD

**Issue by pvalette** [archethic-foundation/archethic-node#1523]
### Describe the problem you discovered

I created a transaction but there is a crash in explorer

https://[testnet.archethic.net/explorer/transaction/00005B002866E38C9F11303EAE810C422E9CF61E8FA794EC966219D5C4D82B32BEA5](https://testnet.archethic.net/explorer/transaction/00005B002866E38C9F11303EAE810C422E9CF61E8FA794EC966219D5C4D82B32BEA5)

I suspect a value in the state attribute

### Describe the solution you'd like

To see the transaction details

**Comment by bchamagne** [comment]
Hi! Thanks for the feedback. 
The issue is that we try to convert to JSON (to display the state "prettified") something that is not valid JSON:

<img width="989" alt="Capture d’écran 2024-06-03 à 09 25 02" src="https://github.com/archethic-foundation/archethic-node/assets/74045243/393295c1-0104-43a0-9d5a-e1b7c9a1abc1">

We have 2 choices: 

1.  add a fallback case where we print the raw object
2. stringify the keys
