### ISSUE TITLE
[Bug]: GetTransactionChain query timeouts after sometime

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#180]
### What happened?

After a long run of cycles, more than 1 hour with self-repair cycle of 1min interval, the database requests `GetTransactionChain` timeouts, maybe caused by the size of a chain to pull.

### What is expected ?

We should be able to read a transaction chain without timeout whatever the size.

**Comment by samuel-uniris** [comment]
Analysis: If the transaction chain is big, the connection can time out and we may not get the transaction chain in sync.

Proposal of solution:

You can provide page parameter into the P2P message.
Also, ScyllaDB /Cassandra provides already paging mechanism, so we can delegate this to the DB without problem.

Request P2P message
```
%GetTransactionChain{
  address: ...
  page: 10
}
```

Returned P2P message
```
%TransactionList{
   transactions: ...
   page: 10;
   more?: true
}
```

Example of the database query:
```
"SELECT * FROM archethic.transaction_chains WHERE address = ? LIMIT ?" 
```

**Comment by akshay-reddy-uniris** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/180?planning-poker) with ZenHub @apoorv-2204 @imnik11 @roychowdhuryrohit-dev @samuel-uniris @nilesh-uniris

**Comment by apoorv-2204** [comment]
hi,
Sam whenever you are feeling well pls then only answer,
Please answer the following questions :
-what topics from elixir I need to study to achieve code of this in non-blocking way?
-what module from archethic node , I need to understand to start understanding the problem?
-What is the exact solution you think  to be  implemented ?

Hi Sam please be very specific , if not  it will be backtracking for me?

**Comment by apoorv-2204** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-IN style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>



Sno | question | Answer/where   can I find the answer?
-- | -- | --
1 | The   timeout is due to network connection is being open for long or keeping the db   connection open for too long? |  
2 | Is   Cassandra being used for writes and Scylla for reads? | Xandra   is used for both cass/scy
3 | Is it   required to store the querier state , in case of connection drop , or we will   leave it to the db? |  
4 | The   size of fetch in one request , or no. of rows to fetch in one request?how   many rows to be sent at once | You can   set a default fetch size globally for a Cluster instance    If the fetch size   is set on a statement, it will take precedence; otherwise, the cluster-wide   value (which defaults to 5000) will be used.From 
5 | It   includes both self-repair and replication ? | I think   yes , both have different module can't pin point of single   getTransactionChain
6 |   |  
7 |   |  
8 |   |  
9 |   |  
10 |   |  



</div>


</body>

</html>

**Comment by samuel-uniris** [comment]
Hi.
In terms of topics to learn, something really new for Elixir, non blocking messaging is another subject but in this case, the modules involved are the `lib/archethic/replication/transaction_context.ex` and `lib/archethic/db/cassandra_impl.ex`.

For you last questions:
1. The timeout is due  to `network connection is being open for long`
2. ScyllaDB and Cassandra are different implementations, you can use one or the other, but ScyllaDB is faster. But they are separated for read or writes.
3. The database connection should not drop with a decent load and paging state.
4. So there are defined pages and they can be customized inside the statement/query to the DB.
5. `Self-Repair` calls the `Replication` context, so inside the Replication it's used.

**Comment by apoorv-2204** [comment]
hello Sir, 

1. In my opinion I feel that I should recreate this similar problem in separate project and then replicate the same here.
2. For non blocking message ,create a process from within the genserver with no links which deals with share of state
  with other node.
3. If the internet connection is getting closed causing a time-out, then the **paging state has to be saved.** 
4. Since the connection is being  timeout due to internet connection , then paging state need to be stored.
5.If the paging is state to be persisted outside the database , then it will be inefficient as the re-query is required.
6.   **Saving Paging State**  https://python-driver.docs.scylladb.com/3.22.3-scylla/query_paging.html
- persisting paging state on the receiver node by sending paging state over the internet.
- persisting paging state in the sender node
( will work better in Internet /node   disconnection , the query results will be destroyed , (inefficient for db) re-querying required)
- leaving it to the scylla db and leveraging that , keeping that connection open but will result in connection timeout

**Comment by samuel-uniris** [comment]
1. to be able to reproduce the case, you create a test in which you simulate latency, with no pagination and then you should get the timeout message.
2. in fact, I think it should be simple recusrive loop, no need of genserver I think.
3/4. the paging state will be retrieved by the result, as it will inform which page is returned.

**Comment by apoorv-2204** [comment]
- [ ]  understanding of modules   :  - [ ]   ArchEthic.DB    - [ ]  ArchEthic.SelfRepair   - [ ]  ArchEthic.Replication
