### ISSUE TITLE
Improve `GetFirstPublicKey` message

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-node#276]
`GetFirstPublicKey` implementation is not clear about the behavior expected and how it's used.
 Actually it should load the first public key, but finally its implementation:

https://github.com/archethic-foundation/archethic-node/blob/819b8af47e63411e5e7fdd9e68cb65921ab58463/lib/archethic/p2p/message.ex#L1229-L1237

We are returning the first transaction public key or not found, but I think you should leverage more: 
https://github.com/archethic-foundation/archethic-node/blob/819b8af47e63411e5e7fdd9e68cb65921ab58463/lib/archethic/transaction_chain.ex#L70-L74

So we would not have not found return, but the just public key passed in case there are not previous public key.

As we are messing with first transaction and first public key concept.
Moreover, we are fetching the transaction data and fields, which will cause more I/O than just fetching the first public key from the indexing.

---

Related to #268

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/276?planning-poker) with ZenHub @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris

**Comment by internet-zero** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/276?planning-poker) with ZenHub @apoorv-2204

**Comment by prix-uniris** [comment]
@samuel-uniris So, should i use only the Indexer to fetch details as per new db impl. 
https://github.com/archethic-foundation/archethic-node/blob/b4e7d2cb8dd7f116f6135660113bc7157bf431fa/lib/archethic/db/embedded_impl/chain_index.ex#L486-L513
Using this function

**Comment by samuel-uniris** [comment]
> @samuel-uniris So, should i use only the Indexer to fetch details as per new db impl. 
> https://github.com/archethic-foundation/archethic-node/blob/b4e7d2cb8dd7f116f6135660113bc7157bf431fa/lib/archethic/db/embedded_impl/chain_index.ex#L486-L513
> Using this function

I guess you can use `EmbeddedImpl.get_first_public_key​(​public_key​)​`

**Comment by prix-uniris** [comment]
So Instead of using TransactionChain.get_first_transaction Here: https://github.com/archethic-foundation/archethic-node/blob/819b8af47e63411e5e7fdd9e68cb65921ab58463/lib/archethic/p2p/message.ex#L1229-L1237
Which eventually calls 
DB.get_first_chain_address()
https://github.com/archethic-foundation/archethic-node/blob/819b8af47e63411e5e7fdd9e68cb65921ab58463/lib/archethic/transaction_chain.ex#L218

So we should use 
TransactionChain.get_first_public_key()  which calls 
DB.get_first_public_key() which eventually calls 
DB.get_first_chain_address()

So, what is required to do for this Issue. 
@samuel-uniris  @blackode  @apoorv-2204

**Comment by prix-uniris** [comment]
So Instead of using TransactionChain.get_first_transaction Here: https://github.com/archethic-foundation/archethic-node/blob/819b8af47e63411e5e7fdd9e68cb65921ab58463/lib/archethic/p2p/message.ex#L1229-L1237
Which eventually calls 
DB.get_first_chain_address()
https://github.com/archethic-foundation/archethic-node/blob/819b8af47e63411e5e7fdd9e68cb65921ab58463/lib/archethic/transaction_chain.ex#L218

So we should use 
TransactionChain.get_first_public_key()  which calls 
DB.get_first_public_key() which eventually calls 
DB.get_first_chain_address()

So, what is required to do for this Issue. 
@samuel-uniris  @blackode  @apoorv-2204

**Comment by prix-uniris** [comment]
Also not exactly sure , what "As we are messing with first transaction and first public key concept." this meant.

**Comment by apoorv-2204** [comment]
> As we are messing with first transaction and first public key concept.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/90304197/163171442-ff2c6e59-df58-4816-a625-2ddf840c0635.png"> , 

Thanks  @blackode for verifying the diagram

**Comment by apoorv-2204** [comment]
> > As we are messing with first transaction and first public key concept.
> @prix-uniris  
>
> <img alt="image" width="510" src="https://user-images.githubusercontent.com/90304197/163171442-ff2c6e59-df58-4816-a625-2ddf840c0635.png"> ,
> 
> Thanks @blackode for verifying the diagram
