### ISSUE TITLE
Poll metrics Error in metrics dashboard during node start

### ISSUE THREAD

**Issue by imnik11** [archethic-foundation/archethic-node#370]
### What happened?

![Screenshot 2022-06-09 125910](https://user-images.githubusercontent.com/45528152/172790774-32fc2d45-d75d-44f8-b5e8-cbbdcf1477f6.png)

Maybe the metrics polling process started before the transaction_validation and it got empty so, it is unable to poll metrics

### What is expected ?

It expected to start normally and give the `archethic_mining_full_transaction_validation_duration => val `, similarly others metrics etc

**Comment by samuel-uniris** [comment]
I think the issue is due to the use Enum.reduce/2 instead of Enum.reduce/3 as with the first one not accumulator is given.
Then if there are not nodes yet available or authorized during the startup when the polling is initiated, Enum.reduce/2 crashes if the list is empty. Hence the accumulator will help.
But another improvement will be to start the poller only when the local is completely initialized.

**Comment by apoorv-2204** [comment]
Hello, Team 
I think  can I take this issue?

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-node/370?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @Neylix @prix-uniris @samuel-uniris
