### ISSUE TITLE
Use asynchronous connection

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/archethic-node#710]
### Describe the problem you discovered

In the `Connection` module, when a host is not reachable we try to reconnect every 500ms. But if the host ip do not exists, the `gen_tcp.connect` will fall in timeout after 4 seconds. This instruction is synchronous and block all new messages in the Genserver, this can perturb other functionnalities.

### Describe the solution you'd like

In the `Connection` module, the function to try to reconnect `transport.handle_connect` should be asynchronous

**Comment by bchamagne** [comment]
Now, when a process calls `send_message` on a connection that is lost, there will be some delay before it is replied `{:error, :closed}` due to the synchronous reconnect you mention. There may even be an `{:error, :timeout}`.

The goal of this issue is to remove that delay and reply `{:error, :closed}` directly. 

There might be a corner case where we `send_message` just after a `start_link`. It will probably reply `{:error, :closed}` because it did not connect yet. We might need a :connecting state to handle it properly.
